# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-deployment
  template:
    metadata:
      labels:
        app: mlflow-deployment
    spec:
      containers:
      - name: mlflow-deployment
        image: ramdoot/mlflow-server:0.1
        imagePullPolicy: Always
        args:
        - --host=0.0.0.0
        - --port=9000
        - --backend-store-uri=mysql+pymysql://kf-user:kf-password@mysql-service.kubeflow.svc.cluster.local:3306/kubeflow
        - --default-artifact-root=file:/tmp
        - --workers=2
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  ports:
    - port: 9002
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: mlflow-deployment

